apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo/charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
